FROM node:22-alpine as build
WORKDIR /app
COPY frontend/package.json frontend/package-lock.json* /app/
RUN npm install || npm i
COPY frontend /app
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
